Ввод ПИНа из стандартного потока ввода-вывод. Исправление ошибок
pavelkhrulev/RtAdmin pull request #8
Opened 2020-10-12 16:22 UTC by lo1ol

1. Добавление возможности передачи ПИН-кода из стандартного потока ввода вывода. 
2. Исправлена ошибка установки политики изменения ПИН-кода по-умолчанию
3. Повышена версия пакета rtPkcs11Ecp

2020-10-15 07:50 UTC, pavelkhrulev requested changes

2020-10-15 07:50 UTC, pavelkhrulev commented on Aktiv.RtAdmin/CommandHandlerBuilder.cs
> +                    if (!string.IsNullOrWhiteSpace(_commandLineOptions.PinFilePath))
А для чего здесь и далее эта проверка? Пин же можно отдать как через файл, так и через какие-то параметры командной строки вроде.

2020-10-15 07:50 UTC, pavelkhrulev commented on Aktiv.RtAdmin/CommandLineParser.cs
> +        public static string getPasswordFromConsole(String displayMessage, char mask = '*')
`getPasswordFromConsole` => `GetPasswordFromConsole`

2020-10-15 07:51 UTC, pavelkhrulev commented on Aktiv.RtAdmin/CommandLineParser.cs
> +        public static string getPasswordFromConsole(String displayMessage, char mask = '*')
`String` => `string`

2020-10-15 09:59 UTC, lo1ol commented on Aktiv.RtAdmin/CommandHandlerBuilder.cs
> +                    if (!string.IsNullOrWhiteSpace(_commandLineOptions.PinFilePath))
Исправил. Теперь выводится пин только в тех случаях, когда не была передана опция -I

2020-10-19 07:26 UTC, pavelkhrulev approved these changes

2020-10-19 07:27 UTC, merged